remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-readme-index
- jekyll-relative-links

color_scheme: dark
search_enabled: true
heading_anchors: true
aux_links: {}
nav_external_links: []

# 啟用 callouts 設定
callouts:
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: blue
  important:
    title: Important
    color: red
  new:
    title: New
    color: green

sass:
  style: compressed