remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-readme-index
- jekyll-relative-links

title: OGOS - OGATA Open Source
description: Welcome to the OGATA Open Source repository, a collection of useful open-source tools and scripts.