remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-readme-index
- jekyll-relative-links

color_scheme: dark
search_enabled: true
heading_anchors: true
aux_links: {}
nav_external_links: []

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

sass:
  style: compressed