system:
  device: "auto"
  num_workers: 4
  pin_memory: true

model:
  architecture_type: "ppo"
  policy_network:
    hidden_sizes: [256, 256]
    activation: "relu"
  value_network:
    hidden_sizes: [256, 256]
    activation: "relu"

learning_mode:
  type: "reinforcement"
  algorithm: "ppo"
  gamma: 0.99
  gae_lambda: 0.95
  clip_ratio: 0.2
  target_kl: 0.01

environment:
  type: "custom"
  max_steps: 1000
  reward_scale: 1.0

training:
  epochs: 500
  steps_per_epoch: 4000
  batch_size: 64
  learning_rate: 3.0e-4 