# 高配置版本（GPU）
system:
  device: "cuda"
  num_workers: 8
  pin_memory: true
  memory_limit: 0.8

model:
  architecture_type: "transformer"
  input_size: 512
  hidden_size: 512
  output_size: 2
  reasoning_steps: 5
  attention_heads: 12
  dropout_rate: 0.1

# ... 其他設置相同但優化為高性能版本 