system:
  device: "auto"
  num_workers: 4
  pin_memory: true
  memory_limit: 0.8

model:
  architecture_type: "gan"
  generator:
    latent_dim: 100
    channels: [512, 256, 128, 64]
    output_size: [64, 64, 3]
  discriminator:
    channels: [64, 128, 256, 512]
    input_size: [64, 64, 3]

learning_mode:
  type: "gan"

data:
  data_type: "image"
  train_path: "data/raw/images"
  image_size: 64
  channels: 3
  format: "jpg"
  augmentation:
    flip: true
    rotate: 10
    normalize: true

training:
  batch_size: 64
  learning_rate:
    generator: 0.0002
    discriminator: 0.0002
  beta1: 0.5
  beta2: 0.999
  epochs: 100 